version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errorlint
    - exhaustive
    - forbidigo
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - intrange
    - ireturn
    - lll
    - makezero
    - misspell
    - mnd
    - modernize
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - testpackage
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    dupl:
      threshold: 100
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: false
      default-case-required: true
      check:
        - switch
        - map
    forbidigo:
      analyze-types: true
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^panic$
        - pattern: ^fmt\.Print.*$
        - pattern: ^exec\.Command$
          msg: use exec.CommandContext instead
    funcorder:
      struct-method: false
    funlen:
      lines: 50
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - octalLiteral
        - paramTypeCombine
        - sloppyReassign
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
      settings:
        hugeParam:
          sizeThreshold: 33
    gocyclo:
      min-complexity: 16
    gosec:
      severity: low
      confidence: low
      config:
        G302: "0600"
        G306: "0600"
    govet:
      enable-all: true
    lll:
      line-length: 140
    misspell:
      locale: UK
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/abrosimov/go-provider
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
